"""Reusable Streamlit UI renderers, tables, buttons, popovers, and formatting helpers."""

from dashboard_core import (
    _failed_messages,
    _format_trend_watch_cell,
    _render_signal_cell,
    _signal_row_colors,
    format_active_table,
    format_closed_table,
    format_futures_table,
    format_options_table,
    highlight_pullback_rows,
    inject_css,
    render_active_trades,
    render_closed_trades,
    render_colored_signal_table,
    render_derivative_analysis_tab,
    render_derivative_stock_action,
    render_exit_signals,
    render_market_regime,
    render_performance_dashboard,
    render_runtime_log_tail,
    render_scan_status,
    render_select_trade_action,
    render_selected_fno_main,
    render_selected_trades_focus,
    render_sidebar,
    render_summary,
    render_top_trade_highlight,
    render_trade_action_table,
    render_trade_cards,
    render_trade_explain_body,
    render_trade_section,
    render_trend_action_table,
    render_trend_watch_sections,
    render_why_trade_action,
)

__all__ = [name for name in globals() if not name.startswith("__")]
